name: Luacheck

on: [push, pull_request]

jobs:
  luacheck:
    name: Lint lua files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: nebularg/actions-luacheck@v1
